name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  playwright-runner:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright API Tests
        run: pnpm run api

      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: API Report
          path: Reports/
          retention-days: 30

      - name: Run Playwright UI Tests
        run: pnpm run ui

      - name: Upload UI Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: UI Report
          path: Reports/
          retention-days: 30
